version: 2
updates:
  # Group all updates into a single pull request
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "update"
    group:
      name: "all-dependencies"
      package-rules:
        - match:
            dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "update"
    group:
      name: "all-dependencies"
      package-rules:
        - match:
            dependency-type: "all"

