version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  groups:
    rust-deps:
      - "*"

- package-ecosystem: cargo
  directory: "/app"
  schedule:
    interval: weekly
  groups:
    rust-deps:
      - "*"
