[package]
name = "app"
version = "0.1.0"
authors = ["Jachym Putta <jachym.putta@yale.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.5", features = ["web"] }
burn = { version = "0.13.2", features = ["wgpu"]}

# Debug
tracing = "0.1.40"
dioxus-logger = "0.5.0"

[build-dependencies]
burn-import = "0.13.0"
