[application]

# App (Project) Name
name = "detypstify"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "public/"

hot_reload = true

[web.app]

# HTML title tag content
title = "Detypstify"
base_path = "detypstify/"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# include `assets` in web platform
[web.resource]

style = ["./tailwind.css", "./main.css" ] # , "./tailwindcss7b3e5b8fafb8d3a6.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
