name: "Build and deploy"

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Dioxus App
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main 
      - run: |
          nix develop -c just app-release
      - uses: crazy-max/ghaction-github-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          target_branch: gh-pages
          build_dir: ./app/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
